using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Routr.SourceGenerator;


[Generator]
public sealed class RouterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var allHandlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetAllHandlerInfo(ctx))
            .Where(static h => h is not null)
            .Collect();

        context.RegisterSourceOutput(allHandlers, static (ctx, handlers) =>
            GenerateOutput(ctx, handlers!));
    }

    private static HandlerInfo? GetAllHandlerInfo(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol is null || symbol.IsAbstract) return null;

        foreach (var iface in symbol.AllInterfaces)
        {
            var def = iface.OriginalDefinition.ToDisplayString();
            if (def == "Routr.IRequestHandler<TRequest, TResponse>")
                return new HandlerInfo(HandlerKind.Request, symbol.ToDisplayString(),
                    iface.TypeArguments[0].ToDisplayString(),
                    iface.TypeArguments[1].ToDisplayString());

            if (def == "Routr.INotificationHandler<TNotification>")
                return new HandlerInfo(HandlerKind.Notification, symbol.ToDisplayString(),
                    iface.TypeArguments[0].ToDisplayString(), null);
        }
        return null;
    }

    private static void GenerateOutput(
        SourceProductionContext ctx,
        ImmutableArray<HandlerInfo> handlers)
    {
        var requestHandlers = handlers.Where(h => h.Kind == HandlerKind.Request).ToImmutableArray();
        var notificationHandlers = handlers.Where(h => h.Kind == HandlerKind.Notification).ToImmutableArray();

        if (!requestHandlers.IsEmpty)
            GenerateSender(ctx, requestHandlers);

        GeneratePublisher(ctx, notificationHandlers);
        GenerateDiExtensions(ctx, requestHandlers, notificationHandlers);
    }

    private static void GenerateSender(
        SourceProductionContext ctx,
        ImmutableArray<HandlerInfo> handlers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Routr;");
        sb.AppendLine();
        sb.AppendLine("public sealed class GeneratedSender : ISender");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _services;");
        sb.AppendLine("    public GeneratedSender(IServiceProvider services) => _services = services;");
        sb.AppendLine();
        sb.AppendLine("    public Task<TResponse> Send<TResponse>(IRequest<TResponse> request, CancellationToken ct = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        return request switch");
        sb.AppendLine("        {");

        foreach (var h in handlers)
            sb.AppendLine(
                $"            {h.RequestType} r => (Task<TResponse>)(object)" +
                $"_services.GetRequiredService<IRequestHandler<{h.RequestType}, {h.ResponseType}>>().Handle(r, ct),");

        sb.AppendLine("            _ => throw new InvalidOperationException($\"No handler for {request.GetType().Name}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("GeneratedSender.g.cs", sb.ToString());
    }

    private static void GeneratePublisher(
        SourceProductionContext ctx,
        ImmutableArray<HandlerInfo> handlers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Routr;");
        sb.AppendLine();
        sb.AppendLine("public sealed class GeneratedPublisher : IPublisher");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _services;");
        sb.AppendLine("    public GeneratedPublisher(IServiceProvider services) => _services = services;");
        sb.AppendLine();
        sb.AppendLine("    public async Task Publish<TNotification>(TNotification notification, CancellationToken ct = default)");
        sb.AppendLine("        where TNotification : INotification");
        sb.AppendLine("    {");

        var grouped = handlers.GroupBy(h => h.RequestType);
        foreach (var group in grouped)
        {
            var varName = Sanitize(group.Key);
            sb.AppendLine($"        if (notification is {group.Key} {varName})");
            sb.AppendLine("        {");
            foreach (var h in group)
                sb.AppendLine($"            await _services.GetRequiredService<{h.HandlerType}>().Handle({varName}, ct);");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("GeneratedPublisher.g.cs", sb.ToString());
    }

    private static void GenerateDiExtensions(
        SourceProductionContext ctx,
        ImmutableArray<HandlerInfo> requestHandlers,
        ImmutableArray<HandlerInfo> notificationHandlers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Routr;");
        sb.AppendLine();
        sb.AppendLine("public static class RoutrServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddRoutrHandlers(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        services.AddTransient<ISender, GeneratedSender>();");
        sb.AppendLine("        services.AddTransient<IPublisher, GeneratedPublisher>();");

        foreach (var h in requestHandlers)
            sb.AppendLine(
                $"        services.AddTransient<IRequestHandler<{h.RequestType}, {h.ResponseType}>, {h.HandlerType}>();");

        foreach (var h in notificationHandlers)
            sb.AppendLine($"        services.AddTransient<{h.HandlerType}>();");

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("RoutrServiceCollectionExtensions.g.cs", sb.ToString());
    }

    private static string Sanitize(string fullName) =>
        fullName.Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace(",", "_").Replace(" ", "");

    private enum HandlerKind { Request, Notification }

    private sealed record HandlerInfo(
        HandlerKind Kind,
        string HandlerType,
        string RequestType,
        string? ResponseType);
}