using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Routr.SourceGenerator;


[Generator]
public sealed class RouterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetHandlerInfo(ctx))
            .Where(static h => h is not null)
            .Collect();

        context.RegisterSourceOutput(handlers, static (ctx, handlers) =>
            GenerateSender(ctx, handlers!));
    }

    private static HandlerInfo? GetHandlerInfo(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol is null || symbol.IsAbstract) return null;

        foreach (var iface in symbol.AllInterfaces)
        {
            if (iface.OriginalDefinition.ToDisplayString() ==
                "Routr.IRequestHandler<TRequest, TResponse>")
            {
                var requestType = iface.TypeArguments[0].ToDisplayString();
                var responseType = iface.TypeArguments[1].ToDisplayString();
                return new HandlerInfo(
                    symbol.ToDisplayString(),
                    requestType,
                    responseType);
            }
        }
        return null;
    }

    private static void GenerateSender(
        SourceProductionContext ctx,
        ImmutableArray<HandlerInfo> handlers)
    {
        if (handlers.IsEmpty) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine("namespace Routr;");
        sb.AppendLine();
        sb.AppendLine("public sealed class GeneratedSender : ISender");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _services;");
        sb.AppendLine();
        sb.AppendLine("    public GeneratedSender(IServiceProvider services)");
        sb.AppendLine("        => _services = services;");
        sb.AppendLine();
        sb.AppendLine("    public Task<TResponse> Send<TResponse>(IRequest<TResponse> request, CancellationToken ct = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        return request switch");
        sb.AppendLine("        {");

        foreach (var h in handlers)
        {
            sb.AppendLine(
                $"            {h.RequestType} r => (Task<TResponse>)(object)" +
                $"(({h.HandlerType})_services.GetService(typeof({h.HandlerType}))).Handle(r, ct),");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException($\"No handler for {request.GetType().Name}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("GeneratedSender.g.cs", sb.ToString());
    }

    private sealed record HandlerInfo(
        string HandlerType,
        string RequestType,
        string ResponseType);
}